name: Python application

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install --upgrade pyinstaller
    - name: Build executable
      run: |
        pyinstaller --onefile -w ZS_spritetool.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ZS_spritetool_release
        path: dist/ZS_spritetool.exe
    - name: Zip archive
      uses: vimtor/action-zip@v1
      with:
          files: dist/ README.md
          dest: Release.zip
    - name: Release build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Latest"
        prerelease: true
        title: "Release Build"
        files: |
          Release.zip
        